#!/bin/bash
cmake .. -DIrrlicht_INCLUDE_DIR=/home/kkrizka/Sources/irrlicht/include/  -DIrrlicht_LIBRARY_DIR=/home/kkrizka/Sources/irrlicht/lib/Linux/ -DCMAKE_BUILD_TYPE=debug -DENABLE_AGEOMETRY=ON -DENABLE_AWEB=ON -DENABLE_ASTART=OFF
