#!/bin/bash

cmake . -DIrrlicht_INCLUDE_DIR=/Users/kkrizka/Sources/irrlicht-1.5/include/  -DIrrlicht_LIBRARY=/Users/kkrizka/Sources/irrlicht-1.5/lib/Linux/ -DCMAKE_BUILD_TYPE=debug -DENABLE_AGEOMETRY=ON -DENABLE_AGEOMETRY_SVN=OFF -GXcode -DENABLE_AWEB=OFF -DENABLE_ASTART=OFF
