#!/bin/bash
cmake . -DIrrlicht_INCLUDE_DIR=/home/kkrizka/Sources/irrlicht-1.5/include/  -DIrrlicht_LIBRARY=/home/kkrizka/Sources/irrlicht-1.5/lib/Linux/ -DCMAKE_BUILD_TYPE=debug -DENABLE_AWEB=OFF -DENABLE_AHIST=OFF -DENABLE_ALABNOTEBOOK=OFF -DENABLE_ASTART=OFF
