MACRO(INSTALL_FILES folder file)
  EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/file)

  SET(SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/${folder}/${file})
  IF( IS_DIRECTORY ${SOURCE} )
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E copy_directory ${SOURCE} ${CMAKE_BINARY_DIR}/${folder}/${file})
    INSTALL(DIRECTORY ${SOURCE} DESTINATION share/amelia/${folder})
  ELSE( IS_DIRECTORY ${SOURCE} )
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E copy ${SOURCE} ${CMAKE_BINARY_DIR}/${folder}/${file})
    INSTALL(FILES ${SOURCE} DESTINATION share/amelia/${folder})
  ENDIF( IS_DIRECTORY ${SOURCE} )

ENDMACRO(INSTALL_FILES)